project:
  type: website

website:
  title: "Courses, Tutorials and Slides"
  navbar:
    title: The Beginner's Guide to Galaxy
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: topics/01_basics_of_sequencing/01_basics_of_sequencing.qmd
        text: Sequencing Basics
      - href: topics/02_read_sequence_information/02_read_sequence_information.qmd
        text: Reads
      - href: topics/03_ncbi_sra_at_glance/03_ncbi_sra_at_glance.qmd
        text: NCBI SRA
      - href: topics/04_intro_to_galaxy/04_intro_to_galaxy.qmd
        text: Galaxy Introduction
      - href: topics/05_galaxy_first_steps/05_galaxy_first_steps.qmd
        text: First steps in Galaxy
      - href: topics/99_flyer/99_flyer.qmd
        text: Flyer
      
  page-footer: 
    right:
      - text: '<p>All content licensed under a <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">Creative Commons Attribution-NonCommercial 4.0 International License</a>.</p>'
    border: true
    background: "#f8f9fa"
        
format:
  html:
    theme: cosmo
    css: styles.css
    code-copy: true
    toc: true

editor: visual

execute: 
  freeze: auto
